### ISSUE TITLE
composer install error

### ISSUE THREAD

**Issue by Winchester37** [netresearch/gls-sdk-api-parcel-processing#1]
![error](https://user-images.githubusercontent.com/15074140/117111557-7b45cd00-ad90-11eb-8351-83206d500710.PNG)

**Comment by mam08ixo** [comment]
The SDK requires a few virtual packages:

* [psr/http-client-implementation](https://packagist.org/providers/psr/http-client-implementation)
* [psr/http-factory-implementation](https://packagist.org/providers/psr/http-factory-implementation)
* [psr/http-message-implementation](https://packagist.org/providers/psr/http-message-implementation)

You are responsible for adding implementations (packages that provide the functionality) to your project yourself. That's basically what the CLI output already tells you.

We usually require [`nyholm/psr7` and `php-http/curl-client`](https://github.com/netresearch/module-shipping-core/blob/2.2.0/composer.json#L46-L47) but you are free to pick any of the providers linked above (e.g. the `guzzlehttp` packages if you plan to use them in your project anyway).
