### ISSUE TITLE
[0004] Error

### ISSUE THREAD

**Issue by Winchester37** [netresearch/gls-sdk-api-parcel-processing#2]
Hi, first of all thank you for your previous help. I have successfully created a barcode (label) with test API information. However, when we enter our own api information, we get an error as follows. I do not know if it is from us or by GLS.

[0004] Input validation error. – An error occurred when validating input: The provided shipper is not allowed to create shipments. [cde056da-a8bb-423e-bf35-03b8c41ffbed]

**Comment by ngolatka** [comment]
Hi @Winchester37 I noticed you closed this issue again.

For questions like this (general technical support) we have a Knowledge Base with a [contact form](https://gls.support.netresearch.de/) – if you or others need help in the future.
